episodeLength: 20
weather: false
map:
    name: 'world'
    size: 2000
    wall:
        height: 128
        block: 7
daylightCycle:
    do: false
    time: 6000
allow-reconnect: true
scoreboard: Kill The Patrick
kick-on-death:
    kick: true
    time: 30
modifications:
    recetteGoldenMelon: true
    boussole: true
positions:
    - '587,593'
    - '592,-278'
    - '-584,-598'
    - '-583,597'
    - '584,2'
    - '-4,-595'
    - '-577,-4'
    - '12,583'
    - '310,278'
    - '384,-103'
    - '-305,-294'
    - '-306,299'
    - '0,30'
    - '445,446'